(()=>{'use strict';
const $=id=>document.getElementById(id), DAY=86400000, KEY='tidal-words-v1';
const day=(t=Date.now())=>{const d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={version:1,goal:20,active:'cet4',books:[],progress:{},days:{},practice:'en-zh',autoRead:true,accent:'en-US'},page='study',mode='new',queue=[],current=null,revealed=false,sessionDone=0,timer,choices=[],choiceAnswered=false;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),4200)}
try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(s.version===1&&s.progress&&s.days&&Array.isArray(s.books))state=s;else toast('备份格式不兼容，已开启新学习记录。')}}catch{toast('无法读取本地记录，请检查浏览器存储权限。')}
const builtin={id:'cet4',name:'四级英语词汇',words:window.CET4||[]};
const allBooks=()=>[builtin,...state.books]; const book=()=>allBooks().find(x=>x.id===state.active)||builtin;
const key=w=>`${state.active}:${w.word.toLowerCase()}`;
function save(){if(window.TidalCloud?.userId&&!window.TidalCloud.ready){toast('账号数据正在载入，请稍后重试。');return false}try{localStorage.setItem(window.TidalCloud?.storageKey||KEY,JSON.stringify(state));window.TidalCloud?.enqueue(state);return true}catch{toast('保存失败：浏览器空间不足，请立即导出学习备份。');return false}}
function stats(){const records=Object.values(state.progress),today=state.days[day()]||{new:[],review:[]};let streak=0,d=new Date();if(!state.days[day()]?.new?.length&&!state.days[day()]?.review?.length)d.setDate(d.getDate()-1);for(let i=0;i<10000;i++){const r=state.days[day(d.getTime())];if(!r||!(r.new.length+r.review.length))break;streak++;d.setDate(d.getDate()-1)}return{learned:records.length,due:Object.entries(state.progress).filter(([k,x])=>k.startsWith(state.active+':' )&&x.due<=Date.now()).length,today,streak}}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function renderMetrics(){const s=stats();$('todayNew').replaceChildren(document.createTextNode(s.today.new.length+' '),node('small','/ '+state.goal));$('due').replaceChildren(document.createTextNode(s.due+' '),node('small','词'));$('learned').replaceChildren(document.createTextNode(s.learned+' '),node('small','词'));$('streak').replaceChildren(document.createTextNode(s.streak+' '),node('small','天'));$('goalBar').style.width=Math.min(100,s.today.new.length/state.goal*100)+'%';$('dueBadge').textContent=s.due;$('goal').value=state.goal;const b=book(),learned=b.words.filter(w=>state.progress[key(w)]).length;const pct=b.words.length?Math.round(learned/b.words.length*100):0;$('progressTitle').textContent=b.name;$('progressText').textContent=`已学习 ${learned} / ${b.words.length} 词`;$('progressPercent').textContent=pct+'%';$('bookProgress').style.width=pct+'%';$('totalNote').textContent=`今日已复习 ${s.today.review.length} 词`;}
function fillBooks(){const el=$('bookSelect');el.replaceChildren();for(const b of allBooks()){const op=node('option',b.name+' · '+b.words.length+' 词');op.value=b.id;el.append(op)}el.value=book().id}
function makeQueue(){const b=book();mode=mode==='review'?'review':'new';queue=b.words.filter(w=>mode==='review'?(state.progress[key(w)]?.due<=Date.now()):!state.progress[key(w)]);if(mode==='new')queue=queue.slice(0,Math.max(0,state.goal-stats().today.new.length));sessionDone=0;next()}
function next(){current=queue.shift()||null;renderCurrent()}
function renderCurrent(){if('speechSynthesis'in window)speechSynthesis.cancel();revealed=false;choiceAnswered=false;choices=[];$('choices').replaceChildren();$('choices').hidden=true;$('quizFeedback').hidden=true;$('continueQuiz').hidden=true;$('answer').hidden=true;$('ratings').hidden=true;$('reveal').hidden=false;$('prompt').hidden=false;$('word').classList.remove('chinese-prompt');$('modeLabel').textContent=mode==='new'?'新词学习':'到期复习';$('sessionLabel').textContent=mode==='new'?'NEW WORDS':'REVIEW';$('queueCount').textContent=`已完成 ${sessionDone} · 剩余 ${queue.length+(current?1:0)}`;$('reveal').disabled=!current;$('speak').hidden=!current;
if(!current){$('word').textContent=mode==='review'?'暂时没有到期单词':'这一程，完成了';$('word').style.fontSize='28px';$('phonetic').textContent='';$('prompt').textContent=mode==='review'?'稍后再来，下一次复习会按计划到达。':'可以去复习计划回顾旧词，或调整每日新词目标。';$('reveal').textContent='本轮已完成';return}
$('word').style.fontSize='';$('word').textContent=current.word;$('phonetic').textContent=current.phonetic||'';$('prompt').textContent='先在心里想一想，这个单词是什么意思？';$('reveal').textContent='查看释义 ↵';$('meaning').textContent=current.meaning;$('example').replaceChildren();if(current.example)$('example').append(node('div',current.example));if(current.exampleCn)$('example').append(node('small',current.exampleCn));const p=state.progress[key(current)];$('hardDelay').textContent=`${Math.max(1,Math.round((p?.interval||1)*1.2))} 天后`;$('goodDelay').textContent=`${p?Math.max(1,Math.round((p.interval||1)*2.3)):1} 天后`;
if(state.practice!=='card')prepareQuiz();else $('keyboardHint').textContent='Enter 查看 · 1 / 2 / 3 评价';
}
function reveal(){if(!current||choices.length)return;revealed=true;$('answer').hidden=false;$('ratings').hidden=false;$('reveal').hidden=true;$('prompt').hidden=true;if(state.autoRead)pronounce(current.word)}
function rate(r,advance=true){if(!current||!revealed||!['again','hard','good'].includes(r))return;const k=key(current),p=state.progress[k],now=Date.now();const interval=r==='again'?10/1440:r==='hard'?Math.max(1,Math.round((p?.interval||1)*1.2)):p?Math.max(1,Math.round((p.interval||1)*2.3)):1;state.progress[k]={due:now+interval*DAY,interval,reps:(p?.reps||0)+1,last:now,rating:r};const d=state.days[day()]??={new:[],review:[]};if(!p){if(!d.new.includes(k))d.new.push(k)}else if(!d.review.includes(k))d.review.push(k);save();sessionDone++;renderMetrics();if(advance)next()}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function meaningParts(w){return w.meaning.replace(/[a-zA-Z.]+/g,'').split(/[，,；;、（）()\s]+/).filter(Boolean)}
function prepareQuiz(){const target=new Set(meaningParts(current)),seen=new Set([current.meaning.trim()]);const distractors=[];for(const w of shuffle([...book().words])){if(w.word.toLowerCase()===current.word.toLowerCase()||seen.has(w.meaning.trim())||meaningParts(w).some(x=>target.has(x)))continue;seen.add(w.meaning.trim());distractors.push(w);if(distractors.length===3)break}if(distractors.length<3){$('prompt').textContent='词库里不同释义不足 4 个，本题使用翻卡学习。';$('keyboardHint').textContent='Enter 查看 · 1 / 2 / 3 评价';return}choices=shuffle([current,...distractors]);$('choices').hidden=false;$('reveal').hidden=true;$('keyboardHint').textContent='1 / 2 / 3 / 4 选择 · Enter 下一词';const reverse=state.practice==='zh-en';$('word').textContent=reverse?current.meaning:current.word;$('word').classList.toggle('chinese-prompt',reverse);$('phonetic').textContent=reverse?'':current.phonetic||'';$('speak').hidden=reverse;$('prompt').textContent=reverse?'选择与这段中文释义对应的英文单词':'选择这个单词对应的中文释义';choices.forEach((w,i)=>{const b=node('button',undefined,'choice');b.append(node('span',String(i+1),'choice-number'),node('span',reverse?w.word:w.meaning));b.onclick=()=>answerChoice(i);$('choices').append(b)})}
function answerChoice(i){if(!current||choiceAnswered||!choices[i])return;choiceAnswered=true;revealed=true;const correct=choices[i]===current;const buttons=[...$('choices').children];buttons.forEach((b,j)=>{b.disabled=true;if(choices[j]===current){b.classList.add('correct');b.append(node('span','✓ 正确','choice-status'))}else if(j===i){b.classList.add('incorrect');b.append(node('span','✕ 选错','choice-status'))}});$('quizFeedback').hidden=false;$('quizFeedback').className=correct?'quiz-feedback correct':'quiz-feedback incorrect';$('quizFeedback').textContent=correct?'答对了！下次复习已安排。':'这次没选对，10 分钟后再回顾一次。';$('answer').hidden=false;$('meaning').textContent=current.word+' · '+current.meaning;$('speak').hidden=false;$('phonetic').textContent=current.phonetic||'';$('continueQuiz').hidden=false;rate(correct?'good':'again',false);$('queueCount').textContent=`已完成 ${sessionDone} · 剩余 ${queue.length}`;if(state.autoRead)pronounce(current.word)}
function pronounce(word){if(!word)return;if(!('speechSynthesis'in window))return toast('当前浏览器暂不支持发音');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang=state.accent||'en-US';const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.replace('_','-')===u.lang)||voices.find(v=>/^en[-_]/i.test(v.lang))||null;u.rate=.85;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('发音暂不可用，请检查系统英文语音包或换用 Edge / Chrome')};speechSynthesis.speak(u)}
function changePage(p){page=p;for(const el of document.querySelectorAll('.page'))el.hidden=el.id!==p;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('pageTitle').textContent={study:'今日学习',review:'复习计划',library:'我的词库',stats:'学习记录'}[p];if(p==='review')renderReview();if(p==='library')renderLibrary();if(p==='stats')renderHistory();renderMetrics()}
function renderReview(){const due=book().words.filter(w=>state.progress[key(w)]?.due<=Date.now());$('reviewNumber').textContent=due.length;$('startReview').disabled=!due.length;$('startReview').textContent=due.length?'开始复习 →':'当前词库暂无到期复习';$('forecast').replaceChildren();const counts=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()+i);const ds=day(date.getTime());return Object.entries(state.progress).filter(([k,p])=>k.startsWith(state.active+':')&&(i===0?p.due<=new Date(ds+'T23:59:59').getTime():day(p.due)===ds)).length});const max=Math.max(1,...counts);counts.forEach((c,i)=>{const col=node('div');col.append(node('span',String(c)));const bar=node('div',undefined,'bar');bar.style.setProperty('--height',Math.max(3,c/max*75)+'px');col.append(bar,node('span',i===0?'今天':`${i} 天后`));$('forecast').append(col)});renderRows($('reviewList'),due.slice(0,80),w=>new Date(state.progress[key(w)].due).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}));if(!due.length)$('reviewList').append(node('p','新学单词会自动出现在这里。','muted'))}
function renderRows(target,words,describe=w=>w.meaning){target.replaceChildren();for(const w of words){const row=node('div',undefined,'word-row');const label=node('div',undefined,'list-word');const sound=node('button','♬','list-speak');sound.setAttribute('aria-label','朗读 '+w.word);sound.onclick=()=>pronounce(w.word);label.append(node('b',w.word),sound);row.append(label,node('span',describe(w)));target.append(row)}}
function renderLibrary(){const wrap=$('books');wrap.replaceChildren();for(const b of allBooks()){const row=node('div',undefined,'book-row');const label=node('div',b.name);label.append(node('small',`　${b.words.length} 词`));const button=node('button',b.id===state.active?'使用中':'切换','secondary');button.disabled=b.id===state.active;button.onclick=()=>{state.active=b.id;save();fillBooks();mode='new';makeQueue();renderLibrary();renderMetrics()};row.append(label,button);wrap.append(row)}search()}
function search(){const q=$('search').value.trim().toLowerCase(),words=book().words.filter(w=>(w.word+' '+w.meaning).toLowerCase().includes(q));renderRows($('wordList'),words.slice(0,100));$('wordList').append(node('p',words.length>100?`共 ${words.length} 个结果，展示前 100 个；输入更多文字缩小范围。`:`共 ${words.length} 个结果`,'muted small'))}
function renderHistory(){const el=$('history');el.replaceChildren();const entries=Array.from({length:14},(_,i)=>{let d=new Date();d.setDate(d.getDate()-13+i);const ds=day(d.getTime()),r=state.days[ds]||{new:[],review:[]};return{ds,r,count:r.new.length+r.review.length}}),max=Math.max(1,...entries.map(x=>x.count));for(const e of entries){const col=node('div');col.title=`${e.ds} 新学 ${e.r.new.length}，复习 ${e.r.review.length}`;col.append(node('span',String(e.count)));const bar=node('div',undefined,'bar');bar.style.setProperty('--height',Math.max(3,e.count/max*90)+'px');col.append(bar,node('span',e.ds.slice(5)));el.append(col)}const s=stats();$('summary').replaceChildren();for(const [label,n]of[['累计学习',s.learned],['学习天数',Object.values(state.days).filter(x=>x.new.length+x.review.length).length],['今日复习',s.today.review.length]]){const item=node('div',label);item.append(node('b',String(n)));$('summary').append(item)}}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=node('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000)}
function csv(text){const rows=[];let row=[],v='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){v+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v=''}else v+=c}if(quoted)throw Error('CSV 引号不匹配');row.push(v);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)throw Error('文件为空');const heads=rows.shift().map(x=>x.replace(/^\uFEFF/,'').trim().toLowerCase());if(!heads.includes('word')||!heads.includes('meaning'))throw Error('CSV 需要 word 和 meaning 列');return rows.map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]||''])))}
function validateWords(data){if(!Array.isArray(data)||!data.length||data.length>20000)throw Error('词库需要包含 1–20000 个单词');const seen=new Set();const arr=[];data.forEach((w,i)=>{if(typeof w?.word!=='string'||typeof w?.meaning!=='string'||!w.word.trim()||!w.meaning.trim())throw Error(`第 ${i+1} 条缺少 word 或 meaning`);const word=w.word.trim();if(word.length>100||w.meaning.length>3000)throw Error(`第 ${i+1} 条内容过长`);const k=word.toLowerCase();if(seen.has(k))return;seen.add(k);arr.push({word,meaning:w.meaning.trim(),phonetic:typeof w.phonetic==='string'?w.phonetic.slice(0,250):'',example:typeof w.example==='string'?w.example.slice(0,2000):'',exampleCn:typeof w.exampleCn==='string'?w.exampleCn.slice(0,2000):''})});return arr}
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10e6)throw Error('文件请小于 10 MB');const text=await f.text();const words=validateWords(f.name.toLowerCase().endsWith('.json')?JSON.parse(text):csv(text));const b={id:crypto.randomUUID?crypto.randomUUID():'book-'+Date.now(),name:f.name.replace(/\.[^.]+$/,'').slice(0,60),words};state.books.push(b);state.active=b.id;if(!save()){state.books.pop();state.active='cet4';return}fillBooks();makeQueue();renderLibrary();renderMetrics();toast(`已导入 ${words.length} 个去重后的单词`)}catch(err){toast('导入失败：'+err.message)}finally{e.target.value=''}};
$('restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>15e6)throw Error('文件过大');const s=JSON.parse(await f.text());if(s.version!==1||!Array.isArray(s.books)||!s.progress||typeof s.progress!=='object'||!s.days||typeof s.days!=='object'||![10,20,30,50,100].includes(s.goal))throw Error('备份格式不正确');for(const b of s.books){if(typeof b.id!=='string'||typeof b.name!=='string')throw Error('词库无效');b.words=validateWords(b.words)}for(const p of Object.values(s.progress)){if(!Number.isFinite(p.due)||!Number.isFinite(p.interval)||p.interval<=0)throw Error('复习记录无效')}for(const d of Object.values(s.days)){if(!Array.isArray(d.new)||!Array.isArray(d.review))throw Error('日期记录无效')}if(!confirm('恢复备份会替换当前浏览器中的全部学习记录，是否继续？'))return;const old=state;state=s;if(!save()){state=old;return}fillBooks();makeQueue();changePage(page);toast('学习记录已恢复')}catch(err){toast('恢复失败：'+err.message)}finally{e.target.value=''}};
$('export').onclick=()=>download('潮汐词笺-学习备份-'+day()+'.json',JSON.stringify(state,null,2));$('template').onclick=()=>download('词库导入模板.csv','\uFEFFword,meaning,phonetic,example\nshore,n. 海岸,/ʃɔːr/,We walked along the shore.\nmemory,n. 记忆,/ˈmeməri/,Practice improves memory.\n','text/csv;charset=utf-8');
$('goal').onchange=()=>{state.goal=Number($('goal').value);save();renderMetrics();if(mode==='new')makeQueue()};$('bookSelect').onchange=()=>{state.active=$('bookSelect').value;mode='new';save();makeQueue();renderMetrics()};$('search').oninput=search;$('reveal').onclick=reveal;document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(b.dataset.rating));document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(b.dataset.page==='study'&&mode!=='new'){mode='new';makeQueue()}changePage(b.dataset.page)});$('startReview').onclick=()=>{mode='review';makeQueue();changePage('study')};$('speak').onclick=()=>{if(!current)return;if(!('speechSynthesis'in window))return toast('当前浏览器暂不支持发音');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=.85;u.onerror=()=>toast('发音暂不可用，请检查浏览器语音支持');speechSynthesis.speak(u)};
document.addEventListener('keydown',e=>{if(page!=='study'||/INPUT|SELECT|TEXTAREA|BUTTON|A/.test(e.target.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(choices.length){if(['1','2','3','4'].includes(e.key)){e.preventDefault();answerChoice(Number(e.key)-1)}else if(e.key==='Enter'&&choiceAnswered){e.preventDefault();next()}return}if(e.target.tagName==='BUTTON'&&e.key==='Enter')return;if(e.key==='Enter'){e.preventDefault();reveal()}if(revealed&&['1','2','3'].includes(e.key))rate(['again','hard','good'][Number(e.key)-1])});
if(!['card','en-zh','zh-en'].includes(state.practice))state.practice='en-zh';state.autoRead=state.autoRead!==false;if(!['en-US','en-GB'].includes(state.accent))state.accent='en-US';$('practice').value=state.practice;$('autoRead').checked=state.autoRead;$('accent').value=state.accent;$('practice').onchange=()=>{state.practice=$('practice').value;save();if(choiceAnswered)next();else renderCurrent()};$('autoRead').onchange=()=>{state.autoRead=$('autoRead').checked;save()};$('accent').onchange=()=>{state.accent=$('accent').value;save()};$('continueQuiz').onclick=next;$('speak').onclick=()=>pronounce(current?.word);
$('date').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'});if(!allBooks().some(b=>b.id===state.active))state.active='cet4';fillBooks();renderMetrics();makeQueue();
setInterval(()=>{renderMetrics();if(page==='review')renderReview()},30000);
window.TidalApp={getState:()=>JSON.parse(JSON.stringify(state)),toast,replaceState(value,reset=true){state=window.TidalState.validate(value);fillBooks();$('practice').value=state.practice;$('autoRead').checked=state.autoRead;$('accent').value=state.accent;if(reset){mode='new';makeQueue()}changePage(page)},lock(locked){document.querySelector('.work-left').inert=locked;$('goal').disabled=locked;document.querySelector('.sidebar nav').inert=locked;$('restore').disabled=locked},guestKey:KEY};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_study_progress',title:'查看背词进度',description:'读取当前浏览器中的学习进度和到期复习数量，不改变数据。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('不接受参数');const s=stats();return{book:book().name,total:book().words.length,learned:s.learned,due:s.due,todayNew:s.today.new.length,todayReview:s.today.review.length,streak:s.streak}}})).catch(()=>{})}catch{}}
})();
